version: '3.2'

networks:
  traefik:
    external:
      name: ${TRAEFIK_NETWORK:-traefik_proxy}

volumes:
  mysqldata:

services:
  webserver:
    image: nginx:alpine
    container_name: slim-nginx
    working_dir: /application
    volumes:
      - ./:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      traefik.enable: "true"
      traefik.http.routers.slim_test.rule: "Host(`slim.local`)"
      traefik.http.routers.slim_test.entrypoints: "web"
#        traefik.http.services.slim_test.loadbalancer.server.port: "8000"
      traefik.docker.network: "${TRAEFIK_NETWORK:-traefik_proxy}"
    ports:
      - "8080:80"
    networks:
      default:
      traefik:

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      args:
        uid: ${CURRENT_UID:-1001}
        gid: ${CURRENT_GID:-1001}
    container_name: slim-php-fpm
    working_dir: /application
    environment:
      - DATABASE_URL=mysql://slim:slim@mysql/slim
    volumes:
      - ./:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    networks:
      default:

  mysql:
    image: mysql:5.7
    container_name: slim-mysql
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "slim"
      MYSQL_USER: "slim"
      MYSQL_PASSWORD: "slim"
    ports:
      - "3307:3306"
    networks:
      default:
